"""
Reproduce the paper, top to bottom.

    python paper/run_all.py              every stage, in order
    python paper/run_all.py --list       what the stages are
    python paper/run_all.py --only s04_rates s05_ridges
    python paper/run_all.py --numbers    only re-gather the numbers report

Each stage is one file in paper/stages/, named sNN_<topic>.py, with:

    STAGE     its name (= the file stem)
    REQUIRES  stages whose cached products it reads
    run()     does the work: tables -> outputs/tables/<stage>/,
              figures -> outputs/figures/<stage>/, numbers -> outputs/numbers/

After the stages, every stage's numbers are gathered into
outputs/paper_numbers.csv and outputs/PAPER_NUMBERS.md: each number the
manuscript quotes, what the code computes now, and MATCH / DIFF / NEW /
EXTERNAL.
"""

from __future__ import annotations

import argparse
import importlib
import sys
import time
from pathlib import Path

import pandas as pd

PAPER = Path(__file__).resolve().parent
sys.path.insert(0, str(PAPER))

from seclib.config import NUM_DIR, OUT_DIR   # noqa: E402


def stages():
    return sorted(p.stem for p in (PAPER / 'stages').glob('s[0-9][0-9]_*.py'))


def run_stage(name):
    mod = importlib.import_module(f'stages.{name}')
    t0 = time.time()
    print(f'\n=== {name} ===')
    mod.run()
    print(f'=== {name} done in {time.time() - t0:.0f} s')


def gather_numbers():
    files = sorted(NUM_DIR.glob('s*.csv'))
    if not files:
        print('no numbers recorded yet')
        return
    df = pd.concat([pd.read_csv(f, dtype=str, keep_default_na=False) for f in files],
                   ignore_index=True)
    df.to_csv(OUT_DIR / 'paper_numbers.csv', index=False)

    order = ['DIFF', 'EXTERNAL', 'MATCH', 'NEW']
    lines = ['# Paper numbers: manuscript vs code', '',
             'Generated by `paper/run_all.py`. One row per number the manuscript '
             'quotes (or that the code adds), with what the code computes now.', '',
             '| status | count |', '|---|---|']
    counts = df.status.value_counts()
    lines += [f'| {s} | {int(counts.get(s, 0))} |' for s in order]
    for st in order:
        sub = df[df.status == st]
        if sub.empty:
            continue
        lines += ['', f'## {st}', '',
                  '| stage | section | what | paper | computed | note |',
                  '|---|---|---|---|---|---|']
        for _, r in sub.iterrows():
            cell = lambda x: str(x).replace('|', '/').replace('\n', ' ')
            lines.append(f"| {r.stage} | {cell(r.section)} | {cell(r.what)} | "
                         f"{cell(r.paper_value)} | {cell(r.computed)} {cell(r.unit)} | "
                         f"{cell(r.note)} |")
    (OUT_DIR / 'PAPER_NUMBERS.md').write_text('\n'.join(lines) + '\n', encoding='utf8')
    print('\nnumbers: ' + ', '.join(f'{s} {int(counts.get(s, 0))}' for s in order)
          + f'  ->  {OUT_DIR / "PAPER_NUMBERS.md"}')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--list', action='store_true')
    ap.add_argument('--only', nargs='*')
    ap.add_argument('--numbers', action='store_true')
    a = ap.parse_args()
    all_stages = stages()
    if a.list:
        for s in all_stages:
            doc = (importlib.import_module(f'stages.{s}').__doc__ or '').strip()
            print(f'{s:28s} {doc.splitlines()[0] if doc else ""}')
        return
    if not a.numbers:
        for s in (a.only or all_stages):
            if s not in all_stages:
                raise SystemExit(f'unknown stage {s}; see --list')
            run_stage(s)
    gather_numbers()


if __name__ == '__main__':
    main()
